export const modeloAlbumVacio = [
  {
    id: 1,
    nombre: "FIFA Mundial",
    abre: "FWC",
    cantidad: 8,
    figus: [
      { idFigurita: "FWC0", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "FWC1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "FWC2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "FWC3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "FWC4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "FWC5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "FWC6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "FWC7", laTengo: false, esRepetida: false, nroRepetida: 0 },
    ],
  },
  {
    id: 2,
    nombre: "FIFA Estadios",
    abre: "FWC",
    cantidad: 11,
    figus: [
      { idFigurita: "FWC8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "FWC9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "FWC10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 3,
    nombre: "FIFA Campeones",
    abre: "FWC",
    cantidad: 11,
    figus: [
      {
        idFigurita: "FWC19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC20",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC21",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC22",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC23",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC24",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC25",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC26",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC27",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC28",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FWC29",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 4,
    nombre: "Qatar",
    abre: "QAT",
    cantidad: 19,
    figus: [
      { idFigurita: "QAT1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "QAT2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "QAT3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "QAT4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "QAT5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "QAT6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "QAT7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "QAT8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "QAT9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "QAT10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "QAT11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "QAT12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "QAT13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "QAT14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "QAT15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "QAT16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "QAT17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "QAT18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "QAT19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 5,
    nombre: "Ecuador",
    abre: "ECU",
    cantidad: 19,
    figus: [
      { idFigurita: "ECU1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ECU2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ECU3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ECU4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ECU5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ECU6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ECU7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ECU8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ECU9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "ECU10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ECU11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ECU12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ECU13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ECU14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ECU15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ECU16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ECU17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ECU18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ECU19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 6,
    nombre: "Senegal",
    abre: "SEN",
    cantidad: 19,
    figus: [
      { idFigurita: "SEN1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SEN2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SEN3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SEN4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SEN5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SEN6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SEN7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SEN8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SEN9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "SEN10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SEN11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SEN12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SEN13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SEN14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SEN15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SEN16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SEN17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SEN18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SEN19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 7,
    nombre: "Países Bajos",
    abre: "NED",
    cantidad: 19,
    figus: [
      { idFigurita: "NED1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "NED2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "NED3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "NED4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "NED5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "NED6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "NED7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "NED8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "NED9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "NED10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "NED11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "NED12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "NED13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "NED14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "NED15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "NED16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "NED17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "NED18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "NED19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 8,
    nombre: "Inglaterra",
    abre: "ENG",
    cantidad: 19,
    figus: [
      { idFigurita: "ENG1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ENG2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ENG3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ENG4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ENG5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ENG6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ENG7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ENG8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ENG9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "ENG10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ENG11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ENG12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ENG13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ENG14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ENG15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ENG16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ENG17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ENG18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ENG19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 9,
    nombre: "Irán",
    abre: "IRN",
    cantidad: 19,
    figus: [
      { idFigurita: "IRN1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "IRN2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "IRN3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "IRN4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "IRN5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "IRN6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "IRN7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "IRN8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "IRN9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "IRN10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "IRN11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "IRN12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "IRN13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "IRN14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "IRN15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "IRN16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "IRN17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "IRN18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "IRN19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 10,
    nombre: "Estados Unidos",
    abre: "USA",
    cantidad: 19,
    figus: [
      { idFigurita: "USA1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "USA2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "USA3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "USA4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "USA5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "USA6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "USA7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "USA8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "USA9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "USA10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "USA11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "USA12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "USA13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "USA14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "USA15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "USA16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "USA17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "USA18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "USA19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 11,
    nombre: "Gales",
    abre: "WAL",
    cantidad: 19,
    figus: [
      { idFigurita: "WAL1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "WAL2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "WAL3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "WAL4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "WAL5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "WAL6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "WAL7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "WAL8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "WAL9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "WAL10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "WAL11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "WAL12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "WAL13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "WAL14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "WAL15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "WAL16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "WAL17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "WAL18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "WAL19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 12,
    nombre: "Argentina",
    abre: "ARG",
    cantidad: 19,
    figus: [
      { idFigurita: "ARG1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ARG2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ARG3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ARG4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ARG5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ARG6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ARG7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ARG8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ARG9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "ARG10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ARG11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ARG12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ARG13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ARG14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ARG15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ARG16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ARG17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ARG18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ARG19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 13,
    nombre: "Arabia Saudita",
    abre: "KSA",
    cantidad: 19,
    figus: [
      { idFigurita: "KSA1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "KSA2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "KSA3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "KSA4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "KSA5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "KSA6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "KSA7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "KSA8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "KSA9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "KSA10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KSA11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KSA12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KSA13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KSA14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KSA15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KSA16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KSA17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KSA18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KSA19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 14,
    nombre: "México",
    abre: "MEX",
    cantidad: 19,
    figus: [
      { idFigurita: "MEX1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "MEX2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "MEX3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "MEX4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "MEX5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "MEX6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "MEX7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "MEX8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "MEX9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "MEX10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MEX11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MEX12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MEX13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MEX14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MEX15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MEX16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MEX17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MEX18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MEX19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 15,
    nombre: "Polonia",
    abre: "POL",
    cantidad: 19,
    figus: [
      { idFigurita: "POL1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "POL2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "POL3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "POL4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "POL5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "POL6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "POL7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "POL8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "POL9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "POL10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POL11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POL12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POL13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POL14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POL15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POL16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POL17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POL18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POL19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 16,
    nombre: "Francia",
    abre: "FRA",
    cantidad: 19,
    figus: [
      { idFigurita: "FRA1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "FRA2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "FRA3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "FRA4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "FRA5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "FRA6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "FRA7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "FRA8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "FRA9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "FRA10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FRA11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FRA12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FRA13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FRA14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FRA15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FRA16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FRA17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FRA18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "FRA19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 17,
    nombre: "Australia",
    abre: "AUS",
    cantidad: 19,
    figus: [
      { idFigurita: "AUS1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "AUS2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "AUS3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "AUS4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "AUS5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "AUS6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "AUS7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "AUS8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "AUS9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "AUS10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "AUS11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "AUS12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "AUS13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "AUS14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "AUS15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "AUS16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "AUS17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "AUS18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "AUS19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 18,
    nombre: "Dinamarca",
    abre: "DEN",
    cantidad: 19,
    figus: [
      { idFigurita: "DEN1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "DEN2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "DEN3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "DEN4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "DEN5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "DEN6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "DEN7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "DEN8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "DEN9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "DEN10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "DEN11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "DEN12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "DEN13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "DEN14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "DEN15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "DEN16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "DEN17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "DEN18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "DEN19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 19,
    nombre: "Túnez",
    abre: "TUN",
    cantidad: 19,
    figus: [
      { idFigurita: "TUN1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "TUN2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "TUN3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "TUN4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "TUN5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "TUN6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "TUN7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "TUN8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "TUN9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "TUN10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "TUN11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "TUN12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "TUN13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "TUN14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "TUN15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "TUN16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "TUN17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "TUN18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "TUN19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 20,
    nombre: "España",
    abre: "ESP",
    cantidad: 19,
    figus: [
      { idFigurita: "ESP1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ESP2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ESP3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ESP4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ESP5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ESP6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ESP7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ESP8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "ESP9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "ESP10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ESP11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ESP12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ESP13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ESP14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ESP15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ESP16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ESP17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ESP18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "ESP19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 21,
    nombre: "Costa Rica",
    abre: "CRC",
    cantidad: 19,
    figus: [
      { idFigurita: "CRC1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CRC2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CRC3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CRC4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CRC5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CRC6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CRC7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CRC8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CRC9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "CRC10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRC11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRC12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRC13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRC14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRC15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRC16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRC17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRC18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRC19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 22,
    nombre: "Alemania",
    abre: "GER",
    cantidad: 19,
    figus: [
      { idFigurita: "GER1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "GER2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "GER3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "GER4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "GER5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "GER6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "GER7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "GER8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "GER9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "GER10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GER11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GER12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GER13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GER14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GER15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GER16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GER17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GER18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GER19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 23,
    nombre: "Japón",
    abre: "JPN",
    cantidad: 19,
    figus: [
      { idFigurita: "JPN1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "JPN2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "JPN3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "JPN4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "JPN5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "JPN6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "JPN7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "JPN8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "JPN9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "JPN10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "JPN11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "JPN12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "JPN13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "JPN14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "JPN15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "JPN16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "JPN17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "JPN18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "JPN19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 24,
    nombre: "Bélgica",
    abre: "BEL",
    cantidad: 19,
    figus: [
      { idFigurita: "BEL1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "BEL2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "BEL3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "BEL4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "BEL5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "BEL6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "BEL7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "BEL8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "BEL9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "BEL10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BEL11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BEL12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BEL13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BEL14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BEL15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BEL16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BEL17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BEL18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BEL19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 25,
    nombre: "Canadá",
    abre: "CAN",
    cantidad: 19,
    figus: [
      { idFigurita: "CAN1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CAN2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CAN3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CAN4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CAN5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CAN6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CAN7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CAN8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CAN9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "CAN10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CAN11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CAN12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CAN13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CAN14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CAN15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CAN16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CAN17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CAN18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CAN19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 26,
    nombre: "Marruecos",
    abre: "MAR",
    cantidad: 19,
    figus: [
      { idFigurita: "MAR1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "MAR2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "MAR3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "MAR4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "MAR5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "MAR6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "MAR7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "MAR8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "MAR9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "MAR10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MAR11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MAR12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MAR13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MAR14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MAR15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MAR16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MAR17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MAR18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "MAR19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 27,
    nombre: "Croacia",
    abre: "CRO",
    cantidad: 19,
    figus: [
      { idFigurita: "CRO1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CRO2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CRO3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CRO4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CRO5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CRO6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CRO7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CRO8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CRO9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "CRO10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRO11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRO12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRO13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRO14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRO15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRO16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRO17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRO18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CRO19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 28,
    nombre: "Brasil",
    abre: "BRA",
    cantidad: 19,
    figus: [
      { idFigurita: "BRA1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "BRA2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "BRA3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "BRA4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "BRA5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "BRA6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "BRA7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "BRA8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "BRA9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "BRA10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BRA11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BRA12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BRA13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BRA14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BRA15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BRA16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BRA17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BRA18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "BRA19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 29,
    nombre: "Serbia",
    abre: "SRB",
    cantidad: 19,
    figus: [
      { idFigurita: "SRB1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SRB2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SRB3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SRB4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SRB5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SRB6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SRB7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SRB8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SRB9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "SRB10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SRB11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SRB12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SRB13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SRB14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SRB15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SRB16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SRB17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SRB18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SRB19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 30,
    nombre: "Suiza",
    abre: "SUI",
    cantidad: 19,
    figus: [
      { idFigurita: "SUI1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SUI2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SUI3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SUI4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SUI5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SUI6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SUI7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SUI8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "SUI9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "SUI10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SUI11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SUI12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SUI13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SUI14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SUI15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SUI16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SUI17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SUI18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "SUI19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 31,
    nombre: "Camerún",
    abre: "CMR",
    cantidad: 19,
    figus: [
      { idFigurita: "CMR1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CMR2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CMR3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CMR4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CMR5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CMR6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CMR7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CMR8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "CMR9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "CMR10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CMR11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CMR12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CMR13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CMR14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CMR15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CMR16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CMR17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CMR18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "CMR19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 32,
    nombre: "Portugal",
    abre: "POR",
    cantidad: 19,
    figus: [
      { idFigurita: "POR1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "POR2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "POR3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "POR4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "POR5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "POR6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "POR7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "POR8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "POR9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "POR10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POR11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POR12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POR13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POR14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POR15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POR16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POR17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POR18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "POR19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 33,
    nombre: "Ghana",
    abre: "GHA",
    cantidad: 19,
    figus: [
      { idFigurita: "GHA1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "GHA2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "GHA3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "GHA4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "GHA5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "GHA6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "GHA7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "GHA8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "GHA9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "GHA10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GHA11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GHA12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GHA13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GHA14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GHA15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GHA16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GHA17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GHA18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "GHA19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 34,
    nombre: "Uruguay",
    abre: "URU",
    cantidad: 19,
    figus: [
      { idFigurita: "URU1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "URU2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "URU3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "URU4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "URU5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "URU6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "URU7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "URU8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "URU9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "URU10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "URU11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "URU12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "URU13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "URU14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "URU15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "URU16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "URU17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "URU18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "URU19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
  {
    id: 35,
    nombre: "Corea del Sur",
    abre: "KOR",
    cantidad: 19,
    figus: [
      { idFigurita: "KOR1", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "KOR2", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "KOR3", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "KOR4", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "KOR5", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "KOR6", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "KOR7", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "KOR8", laTengo: false, esRepetida: false, nroRepetida: 0 },
      { idFigurita: "KOR9", laTengo: false, esRepetida: false, nroRepetida: 0 },
      {
        idFigurita: "KOR10",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KOR11",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KOR12",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KOR13",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KOR14",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KOR15",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KOR16",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KOR17",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KOR18",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
      {
        idFigurita: "KOR19",
        laTengo: false,
        esRepetida: false,
        nroRepetida: 0,
      },
    ],
  },
];
